// Machine-matchable API error codes and their HTTP status mapping,
// per docs/ERROR_HANDLING.md §2. The frontend branches UI behavior on
// these strings; the backend's AllExceptionsFilter is the only place
// that assigns them to an HTTP status.

export const API_ERROR_STATUS_MAP = {
  VALIDATION_ERROR: 400,

  UNAUTHENTICATED: 401,
  INVALID_SIGNATURE: 401,

  FORBIDDEN_ROLE: 403,

  ORGANIZATION_NOT_FOUND: 404,
  EMPLOYEE_NOT_FOUND: 404,
  PAYROLL_RUN_NOT_FOUND: 404,
  CONTRACTOR_NOT_FOUND: 404,
  MILESTONE_NOT_FOUND: 404,
  USER_NOT_FOUND: 404,
  MEMBER_NOT_FOUND: 404,

  SLUG_TAKEN: 409,
  INTENT_ALREADY_SUBMITTED: 409,
  RUN_ALREADY_EXECUTED: 409,
  WALLET_ALREADY_LINKED: 409,
  EMAIL_ALREADY_REGISTERED: 409,

  CHALLENGE_EXPIRED: 410,
  INTENT_EXPIRED: 410,

  INSUFFICIENT_TREASURY_BALANCE: 422,
  INVALID_STATE_TRANSITION: 422,

  CHAIN_SUBMISSION_FAILED: 502,
  SIMULATION_FAILED: 502,

  INTERNAL_ERROR: 500,
} as const;

export type ApiErrorCode = keyof typeof API_ERROR_STATUS_MAP;
